name: Hello World on Merge

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}
          message: "build has been merged"

        uses: khaled-ibtikar/whatsapp-push-notify-action@master
      
      - name : Run
        run: |
          echo 'Start!'
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+15855523680'
          toPhoneNumber: ${{ secrets.to_whatsapp_no }}
          message: 'Hello from Twilio'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.account_sid }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}