name: Hello World on Merge

on:
  push:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
              {
              "blocks": [
                {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "bar"
                }
                }
              ],
              "attachments": [
                {
                "color": "#FF0000",
                "blocks": [
                  {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "foo"
                    }
                  }
                  ]
                }
              ]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}