name: Hello World on PR

on:
  pull_request:
    branches: [ main ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with: 
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java Hello.java